"""empty message

Revision ID: a49bfe0ce5a2
Revises: 3cb4426d44a8
Create Date: 2018-07-11 05:27:25.869900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49bfe0ce5a2'
down_revision = '3cb4426d44a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('comments', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.create_foreign_key(None, 'comments', 'users', ['created_by'], ['id'])
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.alter_column('comments', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_column('comments', 'created_by')
    # ### end Alembic commands ###
